name: Update Configs
permissions:
  contents: write
  
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */8 * * *" # Runs every 6 hours
  workflow_dispatch: # Allows manual runs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: ./Files
        run: pip install -r requirements.txt

      - name: Download and set up Xray
        run: |
          wget -O xray.zip https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-64.zip
          unzip xray.zip xray
          chmod +x xray

      - name: Run main processing script (Fetch & Split)
        working-directory: ./Files
        run: python3 app.py

      - name: Run speed test script (Filter by Speed)
        working-directory: ./Files
        run: python3 speed_tester.py

      - name: Run secure filtering script (Filter by TLS/REALITY)
        working-directory: ./Files
        run: python3 filter_secure.py

      - name: Create per-protocol Base64 lists
        working-directory: ./Files
        run: python3 create_base64_lists.py     


   #  - name: Merge all subscriptions into si
   #    working-directory: ./Splitted-By
   #    run: cat *.txt > all_subscrip



      - name: Merge all subscriptions into single file
        run: |
          # 1. 合并原目录下除了 vless 和 vmess 之外的所有协议 (ss, trojan, hy2 等)
          # 使用 find 命令排除掉不需要的原始文件
          find ./Splitted-By-Protocol -maxdepth 1 -type f -name "*.txt" ! -name "vless.txt" ! -name "vmess.txt" -exec cat {} + > all_subscriptions.txt
          
          # 2. 追加另一个目录中已经过滤好的 vless 和 vmess 文件
          # 使用 -f 判断文件是否存在，防止因为缺少其中一个协议导致 action 报错停止
          [ -f "./Filtered/vless.txt" ] && cat "./Filtered/vless.txt" >> all_subscriptions.txt
          [ -f "./Filtered/vmess.txt" ] && cat "./Filtered/vmess.txt" >> all_subscriptions.txt
          
          echo "合并完成，已排除原始 vless/vmess，并加入过滤后的版本。"



           

      - name: Generate Clash Meta profile
        working-directory: ./Files
        run: python3 generate_clash_profile.py

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "✅ Updated configs and profiles"
          branch: main
          file_pattern: "**/*.txt **/*.yaml"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions Bot <actions@github.com>"
